server:
  port: 8081

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=intern_ordering_order
    username: postgres
    password: 1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: intern_ordering_order

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: intern_ordering_order

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer